<?php
require_once __DIR__.'/../../config/db.php'; require_once __DIR__.'/../../config/session.php'; requireLogin(); if(!isAdmin()) redirect('/modules/payroll/list.php');
$pageTitle='Payroll Timesheet & Report';
$start=$_GET['start']??date('Y-m-d',strtotime('-14 days')); $end=$_GET['end']??date('Y-m-d'); $employee=$_GET['employee_id']??'';
$emps=$pdo->query("SELECT employee_id,first_name,last_name FROM employees WHERE employment_status NOT IN ('Resigned','Terminated') ORDER BY first_name,last_name")->fetchAll();
$sql="SELECT a.*,CONCAT(e.first_name,' ',e.last_name) AS emp_name FROM attendance a JOIN employees e ON e.employee_id=a.employee_id WHERE a.attendance_date BETWEEN ? AND ?"; $params=[$start,$end]; if($employee!==''){ $sql.=' AND a.employee_id=?'; $params[]=$employee; } $sql.=' ORDER BY e.first_name,e.last_name,a.attendance_date'; $st=$pdo->prepare($sql); $st->execute($params); $rows=$st->fetchAll();
include __DIR__.'/../../includes/header.php';
?>
<div class="card"><div class="card-header"><div><h2>Payroll Timesheet / Attendance Records</h2><p class="text-muted">Filter attendance records used as payroll inputs.</p></div><button onclick="window.print()" class="btn btn-secondary">Print Report</button></div>
<form method="get" class="form-grid"><div class="form-group"><label>Employee</label><select name="employee_id"><option value="">All Employees</option><?php foreach($emps as $e): ?><option value="<?= htmlspecialchars($e['employee_id']) ?>" <?= $employee===$e['employee_id']?'selected':'' ?>><?= htmlspecialchars($e['first_name'].' '.$e['last_name']) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Start</label><input type="date" name="start" value="<?= htmlspecialchars($start) ?>"></div><div class="form-group"><label>End</label><input type="date" name="end" value="<?= htmlspecialchars($end) ?>"></div><div class="form-actions" style="align-self:end"><button class="btn btn-primary">Filter Records</button></div></form>
<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Time In</th><th>Time Out</th><th>Status</th><th>Worked Hours</th><th>OT</th><th>Late</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="8" class="empty-state">No timesheet records.</td></tr><?php endif; ?><?php foreach($rows as $r): $mins=0; if($r['time_in']&&$r['time_out']){ $mins=max(0,(strtotime($r['time_out'])-strtotime($r['time_in']))/60); if($r['break_start']&&$r['break_end']) $mins-=max(0,(strtotime($r['break_end'])-strtotime($r['break_start']))/60); } ?><tr><td><?= htmlspecialchars($r['emp_name'].' ('.$r['employee_id'].')') ?></td><td><?= htmlspecialchars($r['attendance_date']) ?></td><td><?= htmlspecialchars($r['time_in']??'—') ?></td><td><?= htmlspecialchars($r['time_out']??'—') ?></td><td><?= htmlspecialchars($r['status']) ?></td><td><?= intdiv((int)$mins,60).'h '.((int)$mins%60).'m' ?></td><td><?= number_format(((int)$r['overtime_minutes'])/60,2) ?>h</td><td><?= (int)$r['late_minutes'] ?>m</td></tr><?php endforeach; ?></tbody></table></div>
<div class="print-footer">HRIS Payroll Timesheet Report · <?= htmlspecialchars(date('M d, Y h:i A')) ?></div></div>
<?php include __DIR__.'/../../includes/footer.php'; ?>