<?php
require_once __DIR__.'/../../config/db.php'; require_once __DIR__.'/../../config/security.php'; requireRole('HR Administrator');
$type=$_GET['type']??'';
$allowed=['employees','attendance','leave','payroll','performance','audit'];
if($type && in_array($type,$allowed,true)){
 $map=['employees'=>"SELECT employee_id,first_name,middle_name,last_name,email,department_id,position_id,employment_status,date_hired,basic_salary FROM employees",'attendance'=>"SELECT attendance_id,employee_id,attendance_date,time_in,time_out,status,late_minutes,overtime_minutes FROM attendance",'leave'=>"SELECT leave_id,employee_id,leave_type,start_date,end_date,total_days,status,date_filed FROM leave_requests",'payroll'=>"SELECT payroll_id,employee_id,pay_period_start,pay_period_end,basic_salary,gross_pay,total_deductions,net_pay,date_generated FROM payroll",'performance'=>"SELECT performance_id,employee_id,evaluation_period,kpi_score,rating,evaluation_date FROM performance",'audit'=>"SELECT audit_id,user_id,employee_id,action,entity,entity_id,details,ip_address,created_at FROM audit_logs"];
 $rows=$pdo->query($map[$type])->fetchAll(); $format=$_GET['format']??'csv'; audit($pdo,'EXPORT',$type,null,strtoupper($format).' export'); if($format==='json'){header('Content-Type:application/json'); header('Content-Disposition:attachment; filename="'.$type.'_'.date('Ymd_His').'.json"'); echo json_encode($rows,JSON_PRETTY_PRINT); exit;} if($format==='print'){ $title=ucfirst($type).' Report'; ?><!doctype html><html><head><meta charset="utf-8"><title><?=htmlspecialchars($title)?></title><style>body{font:14px Arial;padding:30px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:6px;text-align:left}@media print{button{display:none}}</style></head><body>
<a href="#" class="hris-back-btn" data-hris-back="1" onclick="event.preventDefault();history.back();">&#8592; Back</a><h1><?=htmlspecialchars($title)?></h1><button onclick="window.print()">Print</button><table><tr><?php foreach(($rows?array_keys($rows[0]):[]) as $h): ?><th><?=htmlspecialchars($h)?></th><?php endforeach; ?></tr><?php foreach($rows as $r): ?><tr><?php foreach($r as $v): ?><td><?=htmlspecialchars((string)$v)?></td><?php endforeach; ?></tr><?php endforeach; ?></table></body></html><?php exit;} header('Content-Type:text/csv; charset=utf-8'); header('Content-Disposition:attachment; filename="'.$type.'_'.date('Ymd_His').'.csv"'); $out=fopen('php://output','w'); if($rows) fputcsv($out,array_keys($rows[0])); foreach($rows as $r) fputcsv($out,$r); fclose($out); exit;
}
$pageTitle='Reports & Export'; include __DIR__.'/../../includes/header.php';
?>
<div class="card"><h2>Reports & Data Export</h2><p>Export operational HRIS records to CSV for reporting and analysis.</p><div class="export-grid"><?php foreach($allowed as $x): ?><a class="export-card" href="?type=<?= urlencode($x) ?>"><strong><?= ucfirst($x) ?></strong><span>CSV • Excel-compatible • JSON • Print</span><small><a href="?type=<?=urlencode($x)?>&format=json">JSON</a> · <a href="?type=<?=urlencode($x)?>&format=print">Print</a></small></a><?php endforeach; ?></div></div>
<?php include __DIR__.'/../../includes/footer.php'; ?>
